[cosmic-ray]
module-path = "src/main.py"
timeout = 10.0
excluded-modules = []
test-command = "tox py313"

[cosmic-ray.distributor]
name = "local"

[tool.cosmic_ray]
test_runner = "pytest"
target = "src"
tests_dir = "tests"
output = ".cosmic_ray_results"
